#!/bin/bash
# 
# PFX2PEM: Script to convert PFX files to PEM and PEM Key 
# Last updated: August 25 2021 - Tony Mattke
#
VERSION=0.0.1
WHODIDIT="(c) 2021 - Tony Mattke"

DEBUG=0 # 0=off // 1= Dispaly Debug info

EXPECT=/usr/bin/expect
OPENSSL=/usr/bin/openssl

: ${1?"Usage: $0 cert.pfx"}
PFX=$1


function dprint {
  if [ $DEBUG -eq 1 ]; then
    echo \(d\) ${1}
   fi
}


echo "PFX Converter v$VERSION - $WHODIDIT"
echo -e "\nThis script will convert PFX to PEM/PEM key"

if [ ! -f $PFX ] ; then
  echo "Error: File not found $PFX!"
  exit 1
fi

dprint $PFX

EXT=`echo $PFX | cut -d . -f2`
dprint $EXT

KEY=`basename $PFX .$EXT`.key
PEM=`basename $PFX .$EXT`.pem

dprint $KEY
dprint $PEM

echo "Extracting key to ${KEY}"
if [ -f ${KEY} ] ; then
  echo "Error: File ${KEY} already exists!"
  exit 1
fi

openssl pkcs12 -in ${PFX} -nocerts -out ${KEY}
openssl rsa -in ${KEY} -out ${KEY}

echo "Extracting certificate to ${PEM}"
if [ -f ${PEM} ] ; then
  echo "Error: File ${PEM} already exists!"
  exit 1
fi

openssl pkcs12 -in ${PFX} -clcerts -nokeys -out ${PEM}

echo -e "\n Done."
